# Log audit configurations
LogAudit:
        dir: "/var/log/api-em"
        file_name: "audit.log"

# Sample database
DB_Sample: "/etc/api-em/db_sample.sql"

# Skeleton dir
Skeleton: "/home/vinahost/cpanel3-skel/public_html"

# Credential login api
Credential:
        user: "admin"
        password: "uJgLXsQRrX"

# Manage IP
ListIPClient:
        - 123.30.108.100
