# Log audit configurations
LogAudit:
        dir: "/var/log/api-em"
        file_name: "audit.log"

# Sample database
DB_Sample: "/etc/api-em/db_sample.sql"

# Skeleton dir
Skeleton: "/home/vinahost/cpanel3-skel/public_html"

# Credential login api
Credential:
        user: "admin"
        password: "XXXXXXXXXX"

# API listen port
Bind_Port: ":2019"

# Default value
Default:
        ctemail: "haond@vinahost.vn"
        pkgname: "Start"
        owner: "vinahost"

# SSL key
SSL:
        cert: "/etc/api-em/vinahost.crt"
        key: "/etc/api-em/vinahost.key"

# Manage IP
ListIPClient:
        - 123.30.108.100
